### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by renatorib** [aschelch/cakephp-notification-plugin#3]
How can I paginate the notifications?

**Comment by aschelch** [comment]
Hi, 

To paginate notifications, you will have to get notification using a regular CakePHP request.
You associate the NotificationModel in your controller and use the PaginatorComponent

Something like : 

```
    public $uses = array('Notification.Notification');
```

And in your action : 

```
    $this->set('notifications', $this->Paginator->paginate('Notification'));
```
