### ISSUE TITLE
NotificationHelper could not be found

### ISSUE THREAD

**Issue by DavidP-B** [aschelch/cakephp-notification-plugin#4]
I get this error right now. I tried to put it in AppControllers helper array's but the same error. What have I do to import this helper? The error comes in the layout, when I call the method display on Notification Helper.

Thanks!

**Comment by DavidP-B** [comment]
I think I've find the solution. To import this helper you need to write: 'Notification.Notification', that's it, isn't?

**Comment by aschelch** [comment]
Yes, indeed. You need to load the  NotificationHelper from the Notification plugin. So 'Notification.Notification' yes
