### ISSUE TITLE
How to use this plugin in CakePHP 2 ?

### ISSUE THREAD

**Issue by tonyvince** [aschelch/cakephp-notification-plugin#5]
I am getting an error "Table notification_notifications for model Notification was not found in datasource default".

**Comment by aschelch** [comment]
You have to create the table in your database using the file https://github.com/aschelch/cakephp-notification-plugin/blob/master/Config/Schema/schema.sql

**Comment by tonyvince** [comment]
thank you i created the database .But now I am getting a new error
Error: Call to a member function notify() on null
app\Controller\MyController.php
Line 183
the corresponding  code is  
`$this->User->notify($this->Session->read('Auth.User.id'), 'request_add', array('User'=>$this->Session->read('Auth.User.id'),'Request'=>$request_id,'Category'=>$request_category_id));`

I am using CakePHP 2x . Please help

**Comment by aschelch** [comment]
Its not an error from the Notification plugin. Apparently the model User is not loaded in your controller. 

Did you load it ? (using `public $uses = array('User);`)
